import {createRequire} from 'node:module';
import {mkdir,writeFile,stat} from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium,webkit}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/higes/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const base=process.env.SUSHI_TEST_URL||'http://127.0.0.1:5180/';
const output=process.env.SUSHI_ARTIFACT_DIR||'artifacts/town';
await mkdir(output,{recursive:true});
const ids=['craftsman','conveyor_sushi','auto_sushi_machine','marine_food_plant','sushi_ocean_mining','fusion_sushi_converter','luna_sea','freshness_freezer','global_freshness_sync'];
const legacy=()=>({schemaVersion:5,savedAtMs:Date.now(),game:{facilityCounts:Object.fromEntries(ids.map(id=>[id,id==='global_freshness_sync'?0:1])),sushi:1e10,totalSushiEarned:1e10,totalClicks:1500,runPlayTimeMs:300000,endingPhase:'playing',collapseElapsedMs:0,syncCount:0,syncElapsedMs:0,previousRun:null,unlockedAchievementIds:[],purchasedUpgradeIds:[],seenNewsIds:[]}});
const browser=await (process.env.SUSHI_ENGINE==='webkit'?webkit:chromium).launch({headless:true,...(process.env.SUSHI_ENGINE==='webkit'?{}:{channel:'chrome'})});
const results=[],errors=[];
const fresh=async(width=390,height=844,seed=null)=>{
  const context=await browser.newContext({viewport:{width,height},hasTouch:true,isMobile:width<700,reducedMotion:'no-preference'});
  if(seed)await context.addInitScript(save=>{if(!sessionStorage.getItem('town-seeded')){localStorage.setItem('sushi-loopy.save',JSON.stringify(save));sessionStorage.setItem('town-seeded','yes');}},seed);
  const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base,{waitUntil:'networkidle'});
  return {page,context};
};
try{
  for(const [width,height] of [[320,568],[375,568],[390,844],[430,932],[1280,720],[1440,960]]){
    const {page,context}=await fresh(width,height);
    const dimensions=await page.evaluate(()=>({width:innerWidth,height:innerHeight,scrollWidth:document.documentElement.scrollWidth,scrollHeight:document.documentElement.scrollHeight,dock:document.querySelector('.town-dock').getBoundingClientRect().toJSON()}));
    assert.ok(dimensions.scrollWidth<=width,`horizontal overflow ${width}`);
    assert.ok(dimensions.dock.bottom<=height+1,`dock clipped ${width}`);
    await page.screenshot({path:`${output}/${width}-start.png`});
    await page.getByRole('button',{name:'寿司をタップする。長押しでも握れます',exact:true}).press('Enter');
    for(let i=0;i<9;i++)await page.getByRole('button',{name:'寿司をタップする。長押しでも握れます',exact:true}).click();
    await page.getByRole('button',{name:'職人さんを購入',exact:true}).click();
    await page.locator('.town-chef').waitFor();
    assert.equal(await page.locator('.town-building.is-new').count(),1);
    await page.screenshot({path:`${output}/${width}-craftsman.png`});
    results.push({width,height,dimensions,firstPurchase:true});await context.close();
  }
  const {page,context}=await fresh(390,844,legacy());
  assert.equal(await page.locator('.town-building').count(),8);
  assert.equal(await page.locator('.town-building.is-new').count(),0,'migration must not replay purchase');
  await page.screenshot({path:`${output}/390-grown.png`});
  await page.getByRole('button',{name:'模様替え',exact:true}).click();
  await page.getByLabel('お店の名前',{exact:true}).fill('青い海のおすし');
  await page.getByRole('button',{name:'保存',exact:true}).click();
  await page.locator('fieldset').filter({has:page.getByText('のれんの色',{exact:true})}).getByRole('button',{name:'藍',exact:true}).click();
  await page.getByRole('button',{name:'夕暮れ',exact:true}).click();
  await page.getByRole('button',{name:'わたしの街にするを閉じる',exact:true}).click();
  await page.screenshot({path:`${output}/390-evening.png`});
  await page.getByRole('button',{name:'模様替え',exact:true}).click();
  await page.locator('.town-move-list').getByRole('button',{name:'職人さん',exact:false}).click();
  await page.getByRole('button',{name:'海洋食材プラント 1個。この場所へ移動',exact:true}).click();
  await page.locator('.town-undo').waitFor();
  await page.getByRole('button',{name:'配置を元に戻す ↶',exact:true}).click();
  await page.getByRole('button',{name:'記録と設定を開く',exact:true}).click();
  await page.getByRole('button',{name:'アニメーションを停止',exact:true}).click();
  await page.getByRole('button',{name:'記録と設定を閉じる',exact:true}).click();
  const offset1=await page.locator('.town-truck').evaluate(el=>getComputedStyle(el).offsetDistance);
  await page.waitForTimeout(300);
  assert.equal(await page.locator('.town-truck').evaluate(el=>getComputedStyle(el).offsetDistance),offset1);
  await page.getByRole('button',{name:'配達トラックに合図する',exact:true}).click();
  assert.match(await page.locator('.town-message').innerText(),/手を振って/);
  await page.getByRole('button',{name:'猫をなでる',exact:true}).click();
  assert.match(await page.locator('.town-message').innerText(),/ベンチ/);
  await page.getByRole('button',{name:'常連さんの注文を見る',exact:true}).click();
  await page.getByRole('button',{name:'まぐろ',exact:true}).click();
  assert.match(await page.locator('.guest-answer').innerText(),/サーモン/);
  await page.getByRole('button',{name:'サーモン',exact:true}).click();
  assert.match(await page.locator('.guest-history').innerText(),/1皿/);
  assert.ok(await page.getByRole('button',{name:'たまご',exact:true}).isDisabled());
  await page.getByRole('button',{name:'今日のひと皿を閉じる',exact:true}).click();
  await page.getByRole('button',{name:'写真モードを開く',exact:true}).click();
  await page.getByRole('button',{name:'この景色を撮る',exact:true}).click();
  const download=page.waitForEvent('download');
  await page.getByRole('link',{name:'写真を保存 ↓',exact:true}).click();
  await (await download).saveAs(`${output}/town-photo.png`);
  assert.ok((await stat(`${output}/town-photo.png`)).size>200000,'photo must contain the actual town artwork');
  await page.getByRole('button',{name:'街に戻る',exact:true}).click();
  // Auto-save and restore the same isolated browser context.
  await page.waitForTimeout(5200);await page.reload({waitUntil:'networkidle'});
  assert.equal(await page.getByRole('heading',{level:1}).innerText(),'青い海のおすし');
  assert.equal(await page.locator('.weather-evening').count(),1);
  assert.equal(await page.locator('.town-building.is-new').count(),0);
  const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('sushi-loopy.save')));
  assert.equal(saved.schemaVersion,6);assert.equal(saved.game.town.color,'indigo');assert.equal(saved.game.town.ordersServed,1);
  assert.deepEqual(saved.game.town.plots,[0,1,2,3,4,5,6,7,8]);
  results.push({migration:true,customization:true,layoutSwapUndo:true,animationPause:true,guestCooldown:true,photoDownload:true,reload:true});
  await context.close();
  assert.deepEqual(errors,[]);
  await writeFile(`${output}/checks.json`,JSON.stringify({results,errors},null,2));
  console.log(JSON.stringify({results,errors},null,2));
}finally{await browser.close();}
